version: '3'
#перед использованием вынести в каталог который является корневым для обоих проектов
services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    depends_on:
      - rabbitmq
  kafka:
      image: docker.io/bitnami/kafka:3.2
      ports:
        - "9092:9092"
      volumes:
        - "kafka_data:/bitnami"
      environment:
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
        - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      depends_on:
        - zookeeper
  rabbitmq:
    image: rabbitmq
    container_name: rabbit_mq
    ports:
      - "5672:5672"
      - "15672:15672"
  server:
    build: ./bellschool/
    container_name: bell_chool
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_SOURCE_URL: jdbc:postgresql://database:5432/
      DB_NAME: postgres
      SPRING_KAFKA_SERVERS: kafka:9092
      RABBIT_HOST: rabbitmq
    depends_on:
      - database
  restclient:
      build: ./restclient/
      container_name: rest_client
      ports:
        - "8081:8081"
      environment:
        SPRING_KAFKA_SERVERS: kafka:9092
        RABBIT_HOST: rabbitmq
        ADDRESS_SERVER_APPLICATION: server:8080
      depends_on:
        - server
  database:
    image: postgres:latest
    container_name: psql
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
      POSTGRES_DB: postgres
    depends_on:
      - kafka
volumes:
    zookeeper_data:
      driver: local
    kafka_data:
      driver: local
